//go:build linux && !android

// Code generated by internal/wayland/wl/gen; DO NOT EDIT.
// XML file : ./protocols/xdg-shell.xml

// xdg_shell Protocol Copyright:
// 
// Copyright © 2008-2013 Kristian Høgsberg
// Copyright © 2013      Rafael Antognolli
// Copyright © 2013      Jasper St. Pierre
// Copyright © 2010-2013 Intel Corporation
// Copyright © 2015-2017 Samsung Electronics Co., Ltd
// Copyright © 2015-2017 Red Hat Inc.
// 
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef XDG_SHELL_CLIENT_PROTOCOL_H
#define XDG_SHELL_CLIENT_PROTOCOL_H
#include "wayland-util.h"

#ifdef  __cplusplus
extern "C" {
#endif

struct wl_proxy;

typedef int (*proc_wl_proxy_add_listener)(struct wl_proxy *proxy, void (**implementation)(void), void *data);
typedef struct wl_proxy *(*proc_wl_proxy_marshal_flags)(struct wl_proxy *proxy, uint32_t opcode, const struct wl_interface *interface, uint32_t version, uint32_t flags, ...);
typedef uint32_t (*proc_wl_proxy_get_version)(struct wl_proxy *proxy);

struct wl_output;
struct wl_seat;
struct wl_surface;
struct xdg_popup;
struct xdg_positioner;
struct xdg_surface;
struct xdg_toplevel;
struct xdg_wm_base;

#ifndef XDG_WM_BASE_INTERFACE
#define XDG_WM_BASE_INTERFACE
extern const struct wl_interface xdg_wm_base_interface;
#endif
#ifndef XDG_POSITIONER_INTERFACE
#define XDG_POSITIONER_INTERFACE
extern const struct wl_interface xdg_positioner_interface;
#endif
#ifndef XDG_SURFACE_INTERFACE
#define XDG_SURFACE_INTERFACE
extern const struct wl_interface xdg_surface_interface;
#endif
#ifndef XDG_TOPLEVEL_INTERFACE
#define XDG_TOPLEVEL_INTERFACE
extern const struct wl_interface xdg_toplevel_interface;
#endif
#ifndef XDG_POPUP_INTERFACE
#define XDG_POPUP_INTERFACE
extern const struct wl_interface xdg_popup_interface;
#endif

struct xdg_wm_base_listener {
	void (*ping)(void *data, struct xdg_wm_base *xdg_wm_base, uint32_t serial);
};
static inline int gamen_xdg_wm_base_add_listener(void *fp, struct xdg_wm_base *xdg_wm_base, const struct xdg_wm_base_listener *listener, void *data) {
	return ((proc_wl_proxy_add_listener)fp)((struct wl_proxy *) xdg_wm_base, (void (**)(void)) listener, data);
}

static inline void gamen_xdg_wm_base_destroy(void *fp1, void *fp2, struct xdg_wm_base *xdg_wm_base) {
	((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) xdg_wm_base, 0, NULL, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) xdg_wm_base), 1);
}

static inline struct xdg_positioner *gamen_xdg_wm_base_create_positioner(void *fp1, void *fp2, struct xdg_wm_base *xdg_wm_base) {
	struct wl_proxy *id;
	id = ((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) xdg_wm_base, 1, &xdg_positioner_interface, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) xdg_wm_base), 0, NULL);
	return (struct xdg_positioner *) id;
}

static inline struct xdg_surface *gamen_xdg_wm_base_get_xdg_surface(void *fp1, void *fp2, struct xdg_wm_base *xdg_wm_base, struct wl_surface *surface) {
	struct wl_proxy *id;
	id = ((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) xdg_wm_base, 2, &xdg_surface_interface, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) xdg_wm_base), 0, NULL, surface);
	return (struct xdg_surface *) id;
}

static inline void gamen_xdg_wm_base_pong(void *fp1, void *fp2, struct xdg_wm_base *xdg_wm_base, uint32_t serial) {
	((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) xdg_wm_base, 3, NULL, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) xdg_wm_base), 0, serial);
}

static inline void gamen_xdg_positioner_destroy(void *fp1, void *fp2, struct xdg_positioner *xdg_positioner) {
	((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) xdg_positioner, 0, NULL, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) xdg_positioner), 1);
}

static inline void gamen_xdg_positioner_set_size(void *fp1, void *fp2, struct xdg_positioner *xdg_positioner, int32_t width, int32_t height) {
	((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) xdg_positioner, 1, NULL, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) xdg_positioner), 0, width, height);
}

static inline void gamen_xdg_positioner_set_anchor_rect(void *fp1, void *fp2, struct xdg_positioner *xdg_positioner, int32_t x, int32_t y, int32_t width, int32_t height) {
	((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) xdg_positioner, 2, NULL, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) xdg_positioner), 0, x, y, width, height);
}

static inline void gamen_xdg_positioner_set_anchor(void *fp1, void *fp2, struct xdg_positioner *xdg_positioner, uint32_t anchor) {
	((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) xdg_positioner, 3, NULL, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) xdg_positioner), 0, anchor);
}

static inline void gamen_xdg_positioner_set_gravity(void *fp1, void *fp2, struct xdg_positioner *xdg_positioner, uint32_t gravity) {
	((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) xdg_positioner, 4, NULL, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) xdg_positioner), 0, gravity);
}

static inline void gamen_xdg_positioner_set_constraint_adjustment(void *fp1, void *fp2, struct xdg_positioner *xdg_positioner, uint32_t constraint_adjustment) {
	((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) xdg_positioner, 5, NULL, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) xdg_positioner), 0, constraint_adjustment);
}

static inline void gamen_xdg_positioner_set_offset(void *fp1, void *fp2, struct xdg_positioner *xdg_positioner, int32_t x, int32_t y) {
	((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) xdg_positioner, 6, NULL, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) xdg_positioner), 0, x, y);
}

static inline void gamen_xdg_positioner_set_reactive(void *fp1, void *fp2, struct xdg_positioner *xdg_positioner) {
	((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) xdg_positioner, 7, NULL, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) xdg_positioner), 0);
}

static inline void gamen_xdg_positioner_set_parent_size(void *fp1, void *fp2, struct xdg_positioner *xdg_positioner, int32_t parent_width, int32_t parent_height) {
	((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) xdg_positioner, 8, NULL, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) xdg_positioner), 0, parent_width, parent_height);
}

static inline void gamen_xdg_positioner_set_parent_configure(void *fp1, void *fp2, struct xdg_positioner *xdg_positioner, uint32_t serial) {
	((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) xdg_positioner, 9, NULL, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) xdg_positioner), 0, serial);
}

struct xdg_surface_listener {
	void (*configure)(void *data, struct xdg_surface *xdg_surface, uint32_t serial);
};
static inline int gamen_xdg_surface_add_listener(void *fp, struct xdg_surface *xdg_surface, const struct xdg_surface_listener *listener, void *data) {
	return ((proc_wl_proxy_add_listener)fp)((struct wl_proxy *) xdg_surface, (void (**)(void)) listener, data);
}

static inline void gamen_xdg_surface_destroy(void *fp1, void *fp2, struct xdg_surface *xdg_surface) {
	((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) xdg_surface, 0, NULL, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) xdg_surface), 1);
}

static inline struct xdg_toplevel *gamen_xdg_surface_get_toplevel(void *fp1, void *fp2, struct xdg_surface *xdg_surface) {
	struct wl_proxy *id;
	id = ((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) xdg_surface, 1, &xdg_toplevel_interface, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) xdg_surface), 0, NULL);
	return (struct xdg_toplevel *) id;
}

static inline struct xdg_popup *gamen_xdg_surface_get_popup(void *fp1, void *fp2, struct xdg_surface *xdg_surface, struct xdg_surface *parent, struct xdg_positioner *positioner) {
	struct wl_proxy *id;
	id = ((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) xdg_surface, 2, &xdg_popup_interface, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) xdg_surface), 0, NULL, parent, positioner);
	return (struct xdg_popup *) id;
}

static inline void gamen_xdg_surface_set_window_geometry(void *fp1, void *fp2, struct xdg_surface *xdg_surface, int32_t x, int32_t y, int32_t width, int32_t height) {
	((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) xdg_surface, 3, NULL, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) xdg_surface), 0, x, y, width, height);
}

static inline void gamen_xdg_surface_ack_configure(void *fp1, void *fp2, struct xdg_surface *xdg_surface, uint32_t serial) {
	((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) xdg_surface, 4, NULL, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) xdg_surface), 0, serial);
}

struct xdg_toplevel_listener {
	void (*configure)(void *data, struct xdg_toplevel *xdg_toplevel, int32_t width, int32_t height, struct wl_array *states);
	void (*close)(void *data, struct xdg_toplevel *xdg_toplevel);
	void (*configure_bounds)(void *data, struct xdg_toplevel *xdg_toplevel, int32_t width, int32_t height);
	void (*wm_capabilities)(void *data, struct xdg_toplevel *xdg_toplevel, struct wl_array *capabilities);
};
static inline int gamen_xdg_toplevel_add_listener(void *fp, struct xdg_toplevel *xdg_toplevel, const struct xdg_toplevel_listener *listener, void *data) {
	return ((proc_wl_proxy_add_listener)fp)((struct wl_proxy *) xdg_toplevel, (void (**)(void)) listener, data);
}

static inline void gamen_xdg_toplevel_destroy(void *fp1, void *fp2, struct xdg_toplevel *xdg_toplevel) {
	((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) xdg_toplevel, 0, NULL, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) xdg_toplevel), 1);
}

static inline void gamen_xdg_toplevel_set_parent(void *fp1, void *fp2, struct xdg_toplevel *xdg_toplevel, struct xdg_toplevel *parent) {
	((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) xdg_toplevel, 1, NULL, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) xdg_toplevel), 0, parent);
}

static inline void gamen_xdg_toplevel_set_title(void *fp1, void *fp2, struct xdg_toplevel *xdg_toplevel, const char *title) {
	((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) xdg_toplevel, 2, NULL, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) xdg_toplevel), 0, title);
}

static inline void gamen_xdg_toplevel_set_app_id(void *fp1, void *fp2, struct xdg_toplevel *xdg_toplevel, const char *app_id) {
	((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) xdg_toplevel, 3, NULL, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) xdg_toplevel), 0, app_id);
}

static inline void gamen_xdg_toplevel_show_window_menu(void *fp1, void *fp2, struct xdg_toplevel *xdg_toplevel, struct wl_seat *seat, uint32_t serial, int32_t x, int32_t y) {
	((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) xdg_toplevel, 4, NULL, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) xdg_toplevel), 0, seat, serial, x, y);
}

static inline void gamen_xdg_toplevel_move(void *fp1, void *fp2, struct xdg_toplevel *xdg_toplevel, struct wl_seat *seat, uint32_t serial) {
	((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) xdg_toplevel, 5, NULL, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) xdg_toplevel), 0, seat, serial);
}

static inline void gamen_xdg_toplevel_resize(void *fp1, void *fp2, struct xdg_toplevel *xdg_toplevel, struct wl_seat *seat, uint32_t serial, uint32_t edges) {
	((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) xdg_toplevel, 6, NULL, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) xdg_toplevel), 0, seat, serial, edges);
}

static inline void gamen_xdg_toplevel_set_max_size(void *fp1, void *fp2, struct xdg_toplevel *xdg_toplevel, int32_t width, int32_t height) {
	((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) xdg_toplevel, 7, NULL, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) xdg_toplevel), 0, width, height);
}

static inline void gamen_xdg_toplevel_set_min_size(void *fp1, void *fp2, struct xdg_toplevel *xdg_toplevel, int32_t width, int32_t height) {
	((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) xdg_toplevel, 8, NULL, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) xdg_toplevel), 0, width, height);
}

static inline void gamen_xdg_toplevel_set_maximized(void *fp1, void *fp2, struct xdg_toplevel *xdg_toplevel) {
	((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) xdg_toplevel, 9, NULL, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) xdg_toplevel), 0);
}

static inline void gamen_xdg_toplevel_unset_maximized(void *fp1, void *fp2, struct xdg_toplevel *xdg_toplevel) {
	((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) xdg_toplevel, 10, NULL, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) xdg_toplevel), 0);
}

static inline void gamen_xdg_toplevel_set_fullscreen(void *fp1, void *fp2, struct xdg_toplevel *xdg_toplevel, struct wl_output *output) {
	((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) xdg_toplevel, 11, NULL, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) xdg_toplevel), 0, output);
}

static inline void gamen_xdg_toplevel_unset_fullscreen(void *fp1, void *fp2, struct xdg_toplevel *xdg_toplevel) {
	((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) xdg_toplevel, 12, NULL, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) xdg_toplevel), 0);
}

static inline void gamen_xdg_toplevel_set_minimized(void *fp1, void *fp2, struct xdg_toplevel *xdg_toplevel) {
	((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) xdg_toplevel, 13, NULL, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) xdg_toplevel), 0);
}

struct xdg_popup_listener {
	void (*configure)(void *data, struct xdg_popup *xdg_popup, int32_t x, int32_t y, int32_t width, int32_t height);
	void (*popup_done)(void *data, struct xdg_popup *xdg_popup);
	void (*repositioned)(void *data, struct xdg_popup *xdg_popup, uint32_t token);
};
static inline int gamen_xdg_popup_add_listener(void *fp, struct xdg_popup *xdg_popup, const struct xdg_popup_listener *listener, void *data) {
	return ((proc_wl_proxy_add_listener)fp)((struct wl_proxy *) xdg_popup, (void (**)(void)) listener, data);
}

static inline void gamen_xdg_popup_destroy(void *fp1, void *fp2, struct xdg_popup *xdg_popup) {
	((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) xdg_popup, 0, NULL, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) xdg_popup), 1);
}

static inline void gamen_xdg_popup_grab(void *fp1, void *fp2, struct xdg_popup *xdg_popup, struct wl_seat *seat, uint32_t serial) {
	((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) xdg_popup, 1, NULL, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) xdg_popup), 0, seat, serial);
}

static inline void gamen_xdg_popup_reposition(void *fp1, void *fp2, struct xdg_popup *xdg_popup, struct xdg_positioner *positioner, uint32_t token) {
	((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) xdg_popup, 2, NULL, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) xdg_popup), 0, positioner, token);
}


#ifdef __cplusplus
}
#endif


#endif
