//go:build linux && !android

// Code generated by internal/wayland/wl/gen; DO NOT EDIT.
// XML file : ./protocols/xdg-decoration-unstable-v1.xml

// xdg_decoration_unstable_v1 Protocol Copyright:
// 
// Copyright © 2018 Simon Ser
// 
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef XDG_DECORATION_UNSTABLE_V_1_CLIENT_PROTOCOL_H
#define XDG_DECORATION_UNSTABLE_V_1_CLIENT_PROTOCOL_H
#include "wayland-util.h"

#ifdef  __cplusplus
extern "C" {
#endif

struct wl_proxy;

typedef int (*proc_wl_proxy_add_listener)(struct wl_proxy *proxy, void (**implementation)(void), void *data);
typedef struct wl_proxy *(*proc_wl_proxy_marshal_flags)(struct wl_proxy *proxy, uint32_t opcode, const struct wl_interface *interface, uint32_t version, uint32_t flags, ...);
typedef uint32_t (*proc_wl_proxy_get_version)(struct wl_proxy *proxy);

struct xdg_toplevel;
struct zxdg_decoration_manager_v1;
struct zxdg_toplevel_decoration_v1;

#ifndef ZXDG_DECORATION_MANAGER_V_1_INTERFACE
#define ZXDG_DECORATION_MANAGER_V_1_INTERFACE
extern const struct wl_interface zxdg_decoration_manager_v1_interface;
#endif
#ifndef ZXDG_TOPLEVEL_DECORATION_V_1_INTERFACE
#define ZXDG_TOPLEVEL_DECORATION_V_1_INTERFACE
extern const struct wl_interface zxdg_toplevel_decoration_v1_interface;
#endif

static inline void gamen_zxdg_decoration_manager_v1_destroy(void *fp1, void *fp2, struct zxdg_decoration_manager_v1 *zxdg_decoration_manager_v1) {
	((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) zxdg_decoration_manager_v1, 0, NULL, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) zxdg_decoration_manager_v1), 1);
}

static inline struct zxdg_toplevel_decoration_v1 *gamen_zxdg_decoration_manager_v1_get_toplevel_decoration(void *fp1, void *fp2, struct zxdg_decoration_manager_v1 *zxdg_decoration_manager_v1, struct xdg_toplevel *toplevel) {
	struct wl_proxy *id;
	id = ((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) zxdg_decoration_manager_v1, 1, &zxdg_toplevel_decoration_v1_interface, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) zxdg_decoration_manager_v1), 0, NULL, toplevel);
	return (struct zxdg_toplevel_decoration_v1 *) id;
}

struct zxdg_toplevel_decoration_v1_listener {
	void (*configure)(void *data, struct zxdg_toplevel_decoration_v1 *zxdg_toplevel_decoration_v1, uint32_t mode);
};
static inline int gamen_zxdg_toplevel_decoration_v1_add_listener(void *fp, struct zxdg_toplevel_decoration_v1 *zxdg_toplevel_decoration_v1, const struct zxdg_toplevel_decoration_v1_listener *listener, void *data) {
	return ((proc_wl_proxy_add_listener)fp)((struct wl_proxy *) zxdg_toplevel_decoration_v1, (void (**)(void)) listener, data);
}

static inline void gamen_zxdg_toplevel_decoration_v1_destroy(void *fp1, void *fp2, struct zxdg_toplevel_decoration_v1 *zxdg_toplevel_decoration_v1) {
	((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) zxdg_toplevel_decoration_v1, 0, NULL, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) zxdg_toplevel_decoration_v1), 1);
}

static inline void gamen_zxdg_toplevel_decoration_v1_set_mode(void *fp1, void *fp2, struct zxdg_toplevel_decoration_v1 *zxdg_toplevel_decoration_v1, uint32_t mode) {
	((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) zxdg_toplevel_decoration_v1, 1, NULL, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) zxdg_toplevel_decoration_v1), 0, mode);
}

static inline void gamen_zxdg_toplevel_decoration_v1_unset_mode(void *fp1, void *fp2, struct zxdg_toplevel_decoration_v1 *zxdg_toplevel_decoration_v1) {
	((proc_wl_proxy_marshal_flags)fp1)((struct wl_proxy *) zxdg_toplevel_decoration_v1, 2, NULL, ((proc_wl_proxy_get_version)fp2)((struct wl_proxy *) zxdg_toplevel_decoration_v1), 0);
}


#ifdef __cplusplus
}
#endif


#endif
